### ISSUE TITLE
emb_mean and trans_mat

### ISSUE THREAD

**Issue by BinWang28** [Linear95/BinarySentEmb#1]
Many thanks for sharing the code.

I have one question about PCA/Random Projection Methods.
e.g. for PCA, we have to compute the projection matrix. Is it computed from the current working dataset we are testing on or some mixture of datasets?
I see the files for trans_mat.npy and emb_mean.npy are not provided.

**Comment by Linear95** [comment]
Hi Bin, thank you for being interested in our work and sorry for replying late.

For PCA, we calculate the projection matrices on the NLI datasets, for a fair comparison to our proposed method. For random projection, the projection matrices are randomly sampled as mentioned in the paper. The average performance is reported. 

For both two methods, each calculation will have a different projection matrix. Therefore, we did not provide pre-trained matrices for these two methods.
